author: Andy Driver
comments: false
description: Personal blog and musings
excerpt_separator: "<!--more-->"
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
lang: en
paginate: 5
paginate_path: /posts/:num/
permalink: /:categories/:year/:month/:day/:title
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
timezone: UTC
title: andydriver.net
url: "http://andydriver.net"
