author: Andy Driver
title: andydriver.net
description: Personal blog and musings
url: "http://andydriver.net"
lang: en
timezone: UTC
comments: false
excerpt_separator: "<!--more-->"
permalink: /:categories/:year/:month/:day/:title
paginate_path: /posts/:num/
paginate: 5
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
